<?php

namespace AppBundle\Repository;

/**
 * EquipageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipageRepository extends \Doctrine\ORM\EntityRepository
{
}
